prefix: portal
domain: mydomain
app:
  volumeHandle: ocid1.filesystem.oc1.sa_saopaulo_1.aaaaaaaaaaadtnjqm5zhkllqojxwiottmewxgylpobqxk3dpfuys2ylefuyqaaaa:10.0.10.43
db:
  volumeHandle: ocid1.filesystem.oc1.sa_saopaulo_1.aaaaaaaaaaadtnjpm5zhkllqojxwiottmewxgylpobqxk3dpfuys2ylefuyqaaaa:10.0.10.43